#lang racket
(struct list-zip (before after))
(define (make-list-zip x)
  (list-zip '() x))
(define (forward z)
  (match z [(list-zip b a)
            (list-zip (cons (car a) b) (cdr a))]))
(define (backward z)
  (match z [(list-zip b a)
            (list-zip (cdr b) (cons (car b) a))]))
(define (update z elt)
  (match z [(list-zip b a)
            (list-zip b (cons elt (cdr a)))]))
(define (list-zip-to-list z)
  (append (reverse (list-zip-before z)) (list-zip-after z)))